apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: httpd-example
    template: httpd-example
  name: httpd
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: httpd
    name: httpd
  template:
    metadata:
      labels:
        app: httpd
        name: httpd
      name: httpd
    spec:
      containers:
      - image: quay.io/gnunn/simple-httpd:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: httpd-example
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 1000Mi