apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: httpd-example
    template: httpd-example
  name: httpd
spec:
  to:
    kind: Service
    name: httpd
    weight: 100
  wildcardPolicy: None
