apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods
  labels:
    app: httpd-example
    template: httpd-example
  name: httpd
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 8080
  selector:
    name: httpd
